"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
import environ
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DJANGO_DEBUG=(bool, False),
    DATABASE_URL=(str, ""),
    DATABASE_SSL_REQUIRE=(bool, False),
    ALLOWED_HOSTS=(str, ".onrender.com,localhost,127.0.0.1"),
    DB_NAME=(str, ""),
    DB_USER=(str, ""),
    DB_PASSWORD=(str, ""),
    DB_HOST=(str, ""),
    DB_PORT=(str, "5432"),
    EMAIL_BACKEND=(str, ""),
    EMAIL_HOST=(str, "ssl0.ovh.net"),
    EMAIL_PORT=(int, 587),
    EMAIL_USE_TLS=(bool, True),
    EMAIL_USE_SSL=(bool, False),
    EMAIL_HOST_USER=(str, ""),
    EMAIL_HOST_PASSWORD=(str, ""),
    DEFAULT_FROM_EMAIL=(str, ""),
    CONTACT_RECIPIENT_EMAIL=(str, "contact@atecmi.com"),
    DJANGO_SECRET_KEY=(str, ""),
    EMAIL_DEBUG_CONSOLE=(bool, False),
)
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
def _env_bool(value: str | None, default: bool = False) -> bool:
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "y", "on"}


IS_RENDER = os.getenv("RENDER") is not None
DEBUG = _env_bool(os.getenv("DJANGO_DEBUG"), default=not IS_RENDER)

# SECURITY WARNING: keep the secret key used in production secret!
_DEV_SECRET_KEY = (
    "django-insecure-ktv_62d2#q22jt)2llosw4t*3*mwy+^!##b&3id@(d%_uq(z$l"
)
SECRET_KEY = env("DJANGO_SECRET_KEY", default="").strip() or os.getenv(
    "DJANGO_SECRET_KEY", ""
).strip()
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = _DEV_SECRET_KEY
    else:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY must be set in the environment when DEBUG is False."
        )

ALLOWED_HOSTS = [
    host.strip()
    for host in env("ALLOWED_HOSTS").split(",")
    if host.strip()
]

# WhiteNoise static storage:
# - in production: hashed + manifest (requires collectstatic)
# - in local dev: avoid manifest errors while editing templates/assets
if not DEBUG:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_ckeditor_5',
    'core',
    'solutions',
    'blog',
    'expertise',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'DIRS': [BASE_DIR / 'templates'],
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application' 


# Database — agnostique Neon (Render) / PostgreSQL OVH / SQLite local
# Fournir DATABASE_URL (recommandé) ou les variables DB_* discrètes.
# DATABASE_SSL_REQUIRE=True par défaut dès qu'une URL PostgreSQL distante est détectée.

_database_url = env("DATABASE_URL", default="").strip() or os.getenv("DATABASE_URL", "").strip()

if not _database_url:
    _db_name = env("DB_NAME", default="").strip()
    if _db_name:
        _db_user = env("DB_USER", default="")
        _db_password = env("DB_PASSWORD", default="")
        _db_host = env("DB_HOST", default="")
        _db_port = env("DB_PORT", default="5432")
        _database_url = (
            f"postgresql://{_db_user}:{_db_password}@{_db_host}:{_db_port}/{_db_name}"
        )

_database_ssl_require = _env_bool(
    os.getenv("DATABASE_SSL_REQUIRE"),
    default=bool(_database_url and _database_url.startswith("postgres")),
)

if _database_url:
    DATABASES = {
        "default": dj_database_url.config(
            default=_database_url,
            conn_max_age=600,
            ssl_require=_database_ssl_require,
        )
    }
else:
    DATABASES = {
        "default": dj_database_url.config(
            default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
            conn_max_age=600,
        )
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') 

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Images des actualités : Article.image → media/blog/
# Uploads CKEditor 5 : media/django_ckeditor_5/

# ---------------------------------------------------------------------------
# E-mail — configuration flexible (local / Render / OVH)
# ---------------------------------------------------------------------------
# Local (DEBUG=True)              → console par défaut (e-mails dans le terminal)
# Render / prod                   → SMTP si EMAIL_HOST_USER + PASSWORD définis
# Tests Render sans SMTP (Yahoo)  → EMAIL_DEBUG_CONSOLE=True (logs Render)
# Bascule OVH jour J              → remplacer uniquement les variables d'env
# ---------------------------------------------------------------------------

EMAIL_DEBUG_CONSOLE = _env_bool(
    os.getenv("EMAIL_DEBUG_CONSOLE"),
    default=env("EMAIL_DEBUG_CONSOLE"),
)

EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env("EMAIL_PORT")
# Booléens stricts depuis l'environnement (Yahoo: TLS/587 — OVH: SSL/465)
EMAIL_USE_TLS = _env_bool(os.getenv("EMAIL_USE_TLS"), default=env("EMAIL_USE_TLS"))
EMAIL_USE_SSL = _env_bool(os.getenv("EMAIL_USE_SSL"), default=env("EMAIL_USE_SSL"))
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")

_smtp_ready = bool(EMAIL_HOST_USER and EMAIL_HOST_PASSWORD)
_explicit_from_email = env("DEFAULT_FROM_EMAIL", default="").strip()

if _smtp_ready:
    # Yahoo / OVH : l'expéditeur doit correspondre au compte SMTP authentifié
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
elif _explicit_from_email:
    DEFAULT_FROM_EMAIL = _explicit_from_email
elif EMAIL_HOST_USER:
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
else:
    DEFAULT_FROM_EMAIL = "no-reply@localhost"

CONTACT_RECIPIENT_EMAIL = env("CONTACT_RECIPIENT_EMAIL")
SERVER_EMAIL = DEFAULT_FROM_EMAIL

_email_backend_override = env("EMAIL_BACKEND", default="").strip()

if _email_backend_override:
    EMAIL_BACKEND = _email_backend_override
elif EMAIL_DEBUG_CONSOLE:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
elif DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
elif _smtp_ready:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# CKEditor 5 (admin blog) + upload d’images dans le contenu
CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "link",
            "bulletedList",
            "numberedList",
            "blockQuote",
            "|",
            "imageUpload",
            "insertTable",
            "undo",
            "redo",
        ],
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security (enable in production)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
