# Generated by Django 5.2.12 on 2026-03-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('benefits', models.TextField()),
                ('process', models.TextField()),
                ('use_cases', models.TextField()),
                ('image', models.ImageField(upload_to='solutions/')),
            ],
        ),
    ]
